services:

  andevis_react.security.view_access_voter:
    class: Andevis\ReactBundle\Security\ViewAccessVoter
    arguments: [ '@auth.permission_checker', '@service_container']
    public: false
    tags:
      - { name: security.voter, priority: -10 }