<?php

namespace Andevis\ReactBundle;

use Andevis\ReactBundle\UI\ComponentBase\Component;
use Andevis\ReactBundle\DependencyInjection\Compiler\ComponentPass;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\HttpKernel\Bundle\Bundle;

/**
 * Created by PhpStorm.
 * User: EvgenijE
 * Date: 30.11.2017
 * Time: 14:04
 */

class AndevisReactBundle extends Bundle
{
    public function build(ContainerBuilder $container)
    {
        parent::build($container); // TODO: Change the autogenerated stub
        $container->addCompilerPass(new ComponentPass());
        $container->registerForAutoconfiguration(Component::class)
            ->addTag('react.components')
        ;
    }
}